# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 3N1WebSite
email: supgeek.rod@gmail.com
author: Rod
description: > # "Write an awesome description for your new site here. 
    3N1WebSite

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["autolink", "tables", "strikethrough"]
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: demo
    fa-name: send
    url: http://dev4living.com
  - title: github
    fa-name: github
    url: https://github.com/dev4living/3N1WebSite
  - title: Download
    fa-name: download
    url: https://github.com/dev4living/3N1WebSite/releases
